CREATE TABLE "bultos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bultos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"product_id" integer NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"bulto_price" double precision DEFAULT 0 NOT NULL,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cash_movements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cash_movements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"shift_id" integer NOT NULL,
	"type" text NOT NULL,
	"amount" double precision NOT NULL,
	"method" text DEFAULT 'cash' NOT NULL,
	"reason" text DEFAULT '',
	"created_by" text DEFAULT '—' NOT NULL,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "combo_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "combo_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"combo_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "combos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "combos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"combo_price" double precision DEFAULT 0 NOT NULL,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "company" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "company_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text DEFAULT '' NOT NULL,
	"address" text DEFAULT '' NOT NULL,
	"phone" text DEFAULT '' NOT NULL,
	"email" text DEFAULT '' NOT NULL,
	"cuit" text DEFAULT '' NOT NULL,
	"logo" text DEFAULT '' NOT NULL,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "comprobante_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "comprobante_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"comprobante_id" integer NOT NULL,
	"product_id" integer,
	"product_name" text NOT NULL,
	"quantity" double precision DEFAULT 1 NOT NULL,
	"unit_price" double precision NOT NULL,
	"subtotal" double precision NOT NULL,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "comprobantes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "comprobantes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tipo" text NOT NULL,
	"numero" text NOT NULL,
	"cliente_nombre" text DEFAULT 'Consumidor Final' NOT NULL,
	"cliente_cuit" text,
	"cliente_direccion" text,
	"fecha" timestamp DEFAULT now() NOT NULL,
	"payment_method" text,
	"subtotal" double precision DEFAULT 0 NOT NULL,
	"iva" double precision DEFAULT 0 NOT NULL,
	"total" double precision DEFAULT 0 NOT NULL,
	"sale_id" integer,
	"notes" text,
	"created_by" text DEFAULT '—' NOT NULL,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "credit_payments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "credit_payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"customer_id" integer NOT NULL,
	"amount" double precision NOT NULL,
	"date" timestamp DEFAULT now() NOT NULL,
	"notes" text,
	"sale_id" integer,
	"comprobante_id" integer,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "customers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"phone" text,
	"email" text,
	"address" text,
	"cuit" text,
	"credit_balance" double precision DEFAULT 0 NOT NULL,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "expenses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "expenses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	"amount" double precision NOT NULL,
	"category" text NOT NULL,
	"date" text NOT NULL,
	"payment_method" text NOT NULL,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pedido_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pedido_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pedido_id" integer NOT NULL,
	"product_id" integer,
	"product_name" text NOT NULL,
	"quantity" double precision DEFAULT 1 NOT NULL,
	"received_qty" double precision DEFAULT 0 NOT NULL,
	"unit_price" double precision NOT NULL,
	"subtotal" double precision NOT NULL,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pedidos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pedidos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"proveedor_id" integer NOT NULL,
	"date" timestamp DEFAULT now() NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"total" double precision DEFAULT 0 NOT NULL,
	"notes" text,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "plantillas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plantillas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tipo" text NOT NULL,
	"template_html" text NOT NULL,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "price_list_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "price_list_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"price_list_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	"price" double precision,
	"percentage" double precision,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "price_lists" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "price_lists_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "proveedores" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "proveedores_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"phone" text,
	"email" text,
	"address" text,
	"cuit" text,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"password_hash" text NOT NULL,
	"role" text DEFAULT 'custom' NOT NULL,
	"permissions" text DEFAULT '[]' NOT NULL,
	"active" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "invoices" ADD COLUMN "payment_method" text NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "image" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "sale_unit" text DEFAULT 'unit' NOT NULL;--> statement-breakpoint
ALTER TABLE "sales" ADD COLUMN "created_by" text DEFAULT '—' NOT NULL;--> statement-breakpoint
ALTER TABLE "shifts" ADD COLUMN "opening_balance" double precision DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "shifts" ADD COLUMN "declared_cash" double precision;--> statement-breakpoint
ALTER TABLE "shifts" ADD COLUMN "variance" double precision;--> statement-breakpoint
ALTER TABLE "shifts" ADD COLUMN "reconciliation_status" text;--> statement-breakpoint
ALTER TABLE "shifts" ADD COLUMN "reconciled_at" timestamp;--> statement-breakpoint
CREATE INDEX "idx_bultos_store" ON "bultos" USING btree ("store_id");--> statement-breakpoint
CREATE INDEX "idx_cash_movements_shift" ON "cash_movements" USING btree ("shift_id");--> statement-breakpoint
CREATE INDEX "idx_cash_movements_store" ON "cash_movements" USING btree ("store_id");--> statement-breakpoint
CREATE INDEX "idx_combo_items_combo" ON "combo_items" USING btree ("combo_id");--> statement-breakpoint
CREATE INDEX "idx_combos_store" ON "combos" USING btree ("store_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_company_store" ON "company" USING btree ("store_id");--> statement-breakpoint
CREATE INDEX "idx_comprobante_items_comprobante" ON "comprobante_items" USING btree ("comprobante_id");--> statement-breakpoint
CREATE INDEX "idx_comprobantes_store_tipo" ON "comprobantes" USING btree ("store_id","tipo");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_comprobantes_numero" ON "comprobantes" USING btree ("store_id","numero");--> statement-breakpoint
CREATE INDEX "idx_comprobantes_created" ON "comprobantes" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_credit_payments_customer" ON "credit_payments" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "idx_credit_payments_store" ON "credit_payments" USING btree ("store_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_customers_store_name" ON "customers" USING btree ("store_id","name");--> statement-breakpoint
CREATE INDEX "idx_expenses_store" ON "expenses" USING btree ("store_id");--> statement-breakpoint
CREATE INDEX "idx_expenses_date" ON "expenses" USING btree ("date");--> statement-breakpoint
CREATE INDEX "idx_pedido_items_pedido" ON "pedido_items" USING btree ("pedido_id");--> statement-breakpoint
CREATE INDEX "idx_pedidos_store_proveedor" ON "pedidos" USING btree ("store_id","proveedor_id");--> statement-breakpoint
CREATE INDEX "idx_pedidos_store_status" ON "pedidos" USING btree ("store_id","status");--> statement-breakpoint
CREATE INDEX "idx_pedidos_created" ON "pedidos" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_plantillas_store_tipo" ON "plantillas" USING btree ("store_id","tipo");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_price_list_items_list_product" ON "price_list_items" USING btree ("price_list_id","product_id");--> statement-breakpoint
CREATE INDEX "idx_price_lists_store" ON "price_lists" USING btree ("store_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_proveedores_store_name" ON "proveedores" USING btree ("store_id","name");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_users_name" ON "users" USING btree ("name");