CREATE TABLE "purchase_invoice_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "purchase_invoice_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"purchase_invoice_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	"product_name" text NOT NULL,
	"quantity" integer NOT NULL,
	"unit_price" double precision NOT NULL,
	"subtotal" double precision NOT NULL,
	"store_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "purchase_invoices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "purchase_invoices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"store_id" text NOT NULL,
	"proveedor_id" integer NOT NULL,
	"invoice_number" text,
	"total" double precision DEFAULT 0 NOT NULL,
	"notes" text,
	"created_by" text DEFAULT '—' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE INDEX "idx_purchase_invoice_items_invoice" ON "purchase_invoice_items" USING btree ("purchase_invoice_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_invoice_items_product" ON "purchase_invoice_items" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_invoices_store" ON "purchase_invoices" USING btree ("store_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_invoices_proveedor" ON "purchase_invoices" USING btree ("proveedor_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_invoices_created" ON "purchase_invoices" USING btree ("created_at");