CREATE TABLE "afip_config" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "afip_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"store_id" text NOT NULL,
	"cuit" text DEFAULT '' NOT NULL,
	"razon_social" text DEFAULT '' NOT NULL,
	"domicilio" text DEFAULT '' NOT NULL,
	"condicion_iva" text DEFAULT 'monotributo' NOT NULL,
	"punto_venta" integer DEFAULT 1 NOT NULL,
	"ambiente" text DEFAULT 'homo' NOT NULL,
	"activo" integer DEFAULT 0 NOT NULL,
	"exigir_cae" integer DEFAULT 0 NOT NULL,
	"cert" text DEFAULT '' NOT NULL,
	"key" text DEFAULT '' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"sync_status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "comprobantes" ADD COLUMN "cae" text;--> statement-breakpoint
ALTER TABLE "comprobantes" ADD COLUMN "cae_vto" timestamp;--> statement-breakpoint
ALTER TABLE "comprobantes" ADD COLUMN "afip_numero" integer;--> statement-breakpoint
ALTER TABLE "comprobantes" ADD COLUMN "afip_pto_venta" integer;--> statement-breakpoint
ALTER TABLE "comprobantes" ADD COLUMN "afip_tipo" integer;--> statement-breakpoint
ALTER TABLE "comprobantes" ADD COLUMN "afip_status" text DEFAULT 'pending' NOT NULL;--> statement-breakpoint
ALTER TABLE "comprobantes" ADD COLUMN "afip_error" text;--> statement-breakpoint
ALTER TABLE "comprobantes" ADD COLUMN "modo" text DEFAULT 'interno' NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "idx_afip_config_store" ON "afip_config" USING btree ("store_id");